server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    default_type application/json;

    location /.well-known/apple-app-site-association {
        add_header Cache-Control "public, max-age=86400";
        try_files /.well-known/apple-app-site-association =404;
    }

    location /.well-known/assetlinks.json {
        add_header Cache-Control "public, max-age=86400";
        try_files /.well-known/assetlinks.json =404;
    }

    location / {
        return 404;
    }
}
